### PR TITLE
Milestone #3 game_logic

### PR DESCRIPTION
**Pull request by AlduLonghi**
**Tasks for this Milestone**

- [x] Follow the logic raised by the user_interface branch regarding the user's inputs and outputs.

- [x] Take into account different scenarios (game-winning, game cheating, etc).

- [x] Test different cases paying attention to the output.

- [x] Announce a winner or a tie.

- [x] Fix linter errors.

### CODE REVIEW

**Comment by Anna-Myzukina** [comment]
## Hi :clap: 

### You did a great job so far! :+1: 
### Just a few changes before it can be approved:


## [REQUIRED]

##### Implementation details

* [ ] Your project should use different classes (For example: Game, Board and Player). The code of the project should be logically divided between classes,  from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/)

screenshot
* [ ] All game-logic related resources (classes and/or modules) are kept in the `lib` directory, from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/)

screenshot 
* [ ] The code should respect the single responsibility rule for methods (i.e. each method does exactly one thing),
 from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/)

screenshot

* [ ] DRY rule should be respected. E.g. students tend to check winning position for X and O separately instead of creating a method and reuse it, from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/)
screenshot 

```ruby
class Game
  board = ['O', 'X', 'O', 'X', 'O', 'X', 'O', 'X', 'X']

  # bad
  def check_win
    # for rows
    return 'X' if board[0] == board[1] == board[2] == 'X'
    return 'O' if board[0] == board[1] == board[2] == 'O'
    return 'X' if board[3] == board[4] == board[5] == 'X'
    return 'O' if board[3] == board[4] == board[5] == 'O'
    return 'X' if board[6] == board[7] == board[8] == 'X'
    return 'O' if board[6] == board[7] == board[8] == 'O'

    # and analogical as above for columns and diagonals
    # which makes it really long...

  end

  # better
  def check_win(player_symbol)
    # for rows
    all_equal(board[0..2], player_symbol) ||
    all_equal(board[3..5], player_symbol) ||
    all_equal(board[6..8], player_symbol)

    # and analogical as above for columns and diagonals
  end

  def all_equal(subarray, player_symbol)
    return true if subarray.uniq.size == 1 && subarray.uniq == player_symbol
  end
end
```


### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding * <g-emoji class="g-emoji" alias="computer" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4bb.png">computer</g-emoji>

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @AlduLonghi, great job with this project :+1: However, to get our project approved, let us fix the comments made the previous TSE :slightly_smiling_face: 
I WOULD HIGHLIGHT A FEW FROM THE PREVIOUS REVIEW
- Let us structure our code nice as pointed out by the previous TSE. We have a`lib` folder which is empty. Kindly put the methods in the lib folder so  that we don't have everything in the exec file

Kindly implement the changes and submit another code review :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](linkedin.com/in/daniel-larbi-addo/)

**Comment by AlduLonghi** [comment]
Hi Daniel!
Thank you so much for your review. You mentioned the lib folder is empty
but actually has three files in it: logic.rb, messages.rb and board.rb. Do
you mean that I need to change those files?
Thank you again,
Aldana.

**Comment by Anna-Myzukina** [comment]
# [APPROVED]  :heavy_check_mark: 

## Thanks for applying the changes  :+1:

### Go and merge to development.

# :raising_hand:  See you at the next projects.

Happy coding  <g-emoji class="g-emoji" alias="computer" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4bb.png">computer</g-emoji>

**Pull request merged**
